// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://felergfqlhystdqxomlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbGVyZ2ZxbGh5c3RkcXhvbWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTkwMTUsImV4cCI6MjA2NTU3NTAxNX0.QsZOZ1cgAe0lA-B43v_pd3BHuQlEEGmwZmO65r0Kr9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);